siteUid: null
sortOrder: 2
template: /events/month
uriParts:
  - events/month/
  -
    - year
    - '\d{4}'
  - /
  -
    - month
    - '(?:0?[1-9]|1[012])'
uriPattern: 'events/month/<year:\d{4}>/<month:(?:0?[1-9]|1[012])>'
