siteUid: null
sortOrder: 22
template: /calendar/month
uriParts:
  - calendar/month/
  -
    - year
    - '\d{4}'
  - /
  -
    - month
    - '(?:0?[1-9]|1[012])'
uriPattern: 'calendar/month/<year:\d{4}>/<month:(?:0?[1-9]|1[012])>'
