siteUid: null
sortOrder: 42
template: /calendar-demo/month
uriParts:
  - calendar-demo/month/
  -
    - year
    - '\d{4}'
  - /
  -
    - month
    - '(?:0?[1-9]|1[012])'
uriPattern: 'calendar-demo/month/<year:\d{4}>/<month:(?:0?[1-9]|1[012])>'
