color: null
fieldLayouts:
  0cad27d9-0556-413c-9436-8f7061ea89ea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-19T17:21:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fa8f80c5-69e6-476e-ba4f-285df2de1e0b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-19T17:24:05+00:00'
            elementCondition: null
            fieldUid: 6453b749-5f18-4ffc-b62a-393fa9752a52 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a04a7c8-a05a-4392-80f6-639b8c8b954f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-19T17:22:30+00:00'
            elementCondition: null
            fieldUid: 90d007fb-964b-4788-b672-633d855a0058 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df149c24-3e93-493e-a8b3-a4c5973155d2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d9bcbf53-ed6a-4fcd-a867-dd9af3d34fba
        userCondition: null
handle: article
hasTitleField: true
icon: ''
name: Article
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
