color: null
fieldLayouts:
  35e99428-ee82-4979-a12d-417924764e5d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-19T16:09:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b43ea130-509a-442b-a3d1-8e04aff903da
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 094c0554-802b-45e8-b19e-f63fe8a6ccfe
        userCondition: null
handle: backdrop
hasTitleField: true
icon: ''
name: Backdrop
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
