color: teal
fieldLayouts:
  d1624690-a3fe-479a-83d7-781cdacf7885:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-19T09:07:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e4d4e0f2-f9b7-448e-9e0c-70810b7ff9b6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-19T09:26:39+00:00'
            elementCondition: null
            fieldUid: 820e255c-6450-4806-b5ca-85831d8a7c7f # Plain Text
            handle: blogAuthor
            includeInCards: false
            instructions: null
            label: 'Blog Author'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2000fce0-2817-4e46-9ec7-e306665c5a22
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-19T09:11:27+00:00'
            elementCondition: null
            fieldUid: 90d007fb-964b-4788-b672-633d855a0058 # Rich Text
            handle: newsBody
            includeInCards: false
            instructions: null
            label: 'News Body'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f24fe5f9-ec49-4bb4-a7aa-ed1795996734
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bf8f6247-9134-4ad2-ac6f-c786e924b985
        userCondition: null
handle: blog
hasTitleField: true
icon: newspaper
name: Blog
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
