color: yellow
fieldLayouts:
  56e041f1-53c4-4e4f-acd5-cec5b4cac557:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-21T19:37:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Link Label'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f87ac614-b748-4a24-b669-9eaea118007f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-21T19:41:27+00:00'
            elementCondition: null
            fieldUid: 6fded0a5-09f9-4885-9b87-14e039c52a6c # Link Field
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5afa8130-9cdd-4bbc-bb0c-be400fa73dde
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 778be78f-3472-420b-8e5f-4a70d3f46f5f
        userCondition: null
handle: callToAction
hasTitleField: true
icon: arrow-pointer
name: 'Call to Action'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
