color: null
fieldLayouts:
  6f32e4d3-5b6c-42d2-b591-4d6383ab06b8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-14T16:21:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a199cc97-04a1-4cce-82a2-add1c9a977e1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-14T16:24:12+00:00'
            elementCondition: null
            fieldUid: 12ddbb21-575e-4a98-b2de-353d6663fad9 # Event
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ecf7cc1-cd0f-4176-991d-ab39d55a0bcf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-14T16:26:18+00:00'
            elementCondition: null
            fieldUid: 39af2a3a-aab0-4110-beef-2c6c8d52eb26 # Event Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0beeb0a8-632b-4ffb-90f4-54b07b31e7ef
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a4c8efb0-3196-4395-b27c-1d7e308639eb
        userCondition: null
handle: event
hasTitleField: true
icon: calendar-days
name: Event
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
