color: violet
fieldLayouts:
  762d7134-96de-444a-9f1e-39fa76b6ba50:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-20T15:16:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e1e65e66-0158-4fbe-9c4e-9325e1cede36
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-20T18:28:26+00:00'
            elementCondition: null
            fieldUid: 75c8e62e-3242-4d56-90d1-090d035078f6 # Figure Image Full
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 040f0b8f-bbf1-4869-afc1-176ba2db6806
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-20T15:19:29+00:00'
            elementCondition: null
            fieldUid: 820e255c-6450-4806-b5ca-85831d8a7c7f # Plain Text
            handle: figureCaption
            includeInCards: false
            instructions: null
            label: 'Figure Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75a6ecf6-6897-4e73-a7f3-ce9678bf3ba1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2de0b7c0-d798-4dd9-839d-1265ea212673
        userCondition: null
handle: figureImageFull
hasTitleField: false
icon: image-polaroid
name: 'Figure Image Full'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
