color: violet
fieldLayouts:
  ebcfc2b2-c56d-4d94-9d16-5d6c456e6cf1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-27T12:16:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0f5833f5-4fe1-4486-a899-2fcc03466ce2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-27T12:18:23+00:00'
            elementCondition: null
            fieldUid: 46c2bc01-7fec-4a8d-9e8f-c578c727a0e3 # Figure Image Right
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86b6f6c9-bc98-4d64-a05c-6a11d4029ab5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-27T12:18:23+00:00'
            elementCondition: null
            fieldUid: 820e255c-6450-4806-b5ca-85831d8a7c7f # Plain Text
            handle: figureCaption
            includeInCards: false
            instructions: null
            label: 'Figure Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 854c2600-e866-4c8d-842a-a7b12ff12648
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: caa638cd-edbd-4c13-8ef1-02ca3eff1c04
        userCondition: null
handle: figureImageRight
hasTitleField: false
icon: image
name: 'Figure Image Right'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
