color: null
fieldLayouts:
  ce16b470-f54f-4774-8fd0-0251cee356aa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-19T01:34:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8e16b4a7-b7f0-4c48-94ce-ccefe974085a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-19T01:39:42+00:00'
            elementCondition: null
            fieldUid: 90d007fb-964b-4788-b672-633d855a0058 # Rich Text
            handle: homepageContent
            includeInCards: false
            instructions: null
            label: Content
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c5178b9-f146-4ae7-ad0c-109afb5e3bd9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d1e042f1-476f-4c6c-b11a-e258c4f4e3bd
        userCondition: null
handle: homepage
hasTitleField: true
icon: house
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
