color: null
fieldLayouts:
  ce16b470-f54f-4774-8fd0-0251cee356aa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-19T01:34:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8e16b4a7-b7f0-4c48-94ce-ccefe974085a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T17:06:33+00:00'
            elementCondition: null
            fieldUid: 820e255c-6450-4806-b5ca-85831d8a7c7f # Plain Text
            handle: headerIntroduction
            includeInCards: false
            instructions: null
            label: 'Header Introduction'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae877276-cb9d-4d63-87bb-2b323cdd174a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T14:13:58+00:00'
            elementCondition: null
            fieldUid: 4024edd3-9d2b-446a-a6dd-48f15e0fc637 # Featured Pages
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfa14652-f970-4ca1-b4bb-d42d6fbdb85e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T17:33:03+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: b584317a-bdbf-49ab-8e67-6a4c97f550e5
            userCondition: null
          -
            dateAdded: '2024-11-03T17:33:03+00:00'
            elementCondition: null
            fieldUid: e404e713-c6b5-42aa-9614-6eab00ed8cc5 # Spotlight Video URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abb21574-d888-4185-9577-f3360b53f724
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-04T11:01:27+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 7561c24b-230b-4f2d-9224-fe623d21d53e
            userCondition: null
          -
            dateAdded: '2024-11-04T11:01:27+00:00'
            elementCondition: null
            fieldUid: 96916aa2-1b5e-429b-85fa-747aa201e6dc # Feature Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90aad229-6bb5-4bf1-bbb2-1f206f55e676
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-04T11:01:27+00:00'
            elementCondition: null
            fieldUid: 90d007fb-964b-4788-b672-633d855a0058 # Rich Text
            handle: featureText
            includeInCards: false
            instructions: null
            label: 'Feature Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3d7943c-1364-4cee-81d0-606a6fd9eccb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-04T11:02:37+00:00'
            elementCondition: null
            fieldUid: 6fded0a5-09f9-4885-9b87-14e039c52a6c # Link Field
            handle: featureLink
            includeInCards: false
            instructions: null
            label: 'Feature Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bc9c36b-7c01-4b52-ab24-6e4408bf9a7c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d1e042f1-476f-4c6c-b11a-e258c4f4e3bd
        userCondition: null
handle: homepageLayout
hasTitleField: false
icon: house
name: 'Homepage Layout'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
