color: null
fieldLayouts:
  ce829a3c-76e2-41a5-897d-9d79dc52fcf2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-19T01:18:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 13aa9112-b5b7-48d8-b4ac-9d747f3f7f3a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68c6834d-5c4a-449a-8321-028a8fd591b4
        userCondition: null
handle: introductionTitle
hasTitleField: true
icon: ''
name: 'Introduction Title'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
