color: null
fieldLayouts:
  0cad27d9-0556-413c-9436-8f7061ea89ea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-19T17:21:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Page Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fa8f80c5-69e6-476e-ba4f-285df2de1e0b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-27T11:06:27+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: d229339b-b194-438f-a753-879d9b859fd2
            userCondition: null
          -
            dateAdded: '2024-10-19T17:24:05+00:00'
            elementCondition: null
            fieldUid: 6453b749-5f18-4ffc-b62a-393fa9752a52 # Hero Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a04a7c8-a05a-4392-80f6-639b8c8b954f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-20T15:48:36+00:00'
            elementCondition: null
            fieldUid: 820e255c-6450-4806-b5ca-85831d8a7c7f # Plain Text
            handle: heroCaption
            includeInCards: false
            instructions: null
            label: 'Hero Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dede1c86-a414-4f84-ac15-6cd6f41abbc2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-27T11:06:27+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: e693cec1-b03a-4470-8830-cd848b8d01b6
            userCondition: null
          -
            dateAdded: '2024-10-20T15:53:26+00:00'
            elementCondition: null
            fieldUid: 820a6717-36a8-4b5c-819b-cbdc9e036334 # Article Content Matrix
            handle: articleContent
            includeInCards: false
            instructions: null
            label: 'Article Content'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e9efdcc-413f-4cfb-8bba-7efee690376e
            userCondition: null
            warning: null
            width: 100
        name: 'Meta Data'
        uid: d9bcbf53-ed6a-4fcd-a867-dd9af3d34fba
        userCondition: null
handle: primaryPageArticle
hasTitleField: true
icon: memo
name: 'Primary Page Article'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
