color: null
fieldLayouts:
  9d323f05-9d66-42a2-83fc-c069a4e5f7ba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-03T15:07:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4023a3d8-970e-4fd6-a0ab-6740cf674e11
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T15:09:22+00:00'
            elementCondition: null
            fieldUid: 90d007fb-964b-4788-b672-633d855a0058 # Event Details
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b941901d-770e-4c49-842b-6bcd378cc983
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T15:09:22+00:00'
            elementCondition: null
            fieldUid: 8827b8d4-2266-4f88-840c-c506b19dafb0 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28bf779f-a8bd-4b30-9222-d3ff5ab42228
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2bbee1db-430e-4998-865f-07104e73faa9
        userCondition: null
handle: specialtyBanner
hasTitleField: true
icon: ''
name: 'Specialty Banner'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
