color: null
fieldLayouts:
  224e26dd-e94f-4011-8736-95a3aec2bf9f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-26T16:54:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ac8af19a-4a7c-4bd7-86d4-02e094a354a6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-26T16:59:21+00:00'
            elementCondition: null
            fieldUid: f8355048-22c0-4c2d-8873-4db92a78ab46 # Virtual Tour Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10ca4c9c-0548-4871-9027-6abbdfbfc2bc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: be847f57-f82b-4f12-b72b-51eeab95e3ea
        userCondition: null
handle: virtualTourImage
hasTitleField: false
icon: null
name: 'Virtual Tour Image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
