allowRepeatingEvents: true
color: '#C82CA9'
description: 'The default calendar'
descriptionFieldHandle: null
fieldLayout: null
handle: default
hasTitleField: true
icsHash: null
icsTimezone: floating
locationFieldHandle: null
name: Default
siteSettings:
  75715ef5-cd56-4c71-9c66-6ec84ecec42e:
    enabledByDefault: true
    hasUrls: null
    siteId: f627def0-bb59-4992-ae44-aef0dfb97c08 # Little Church
    template: null
    uriFormat: null
titleFormat: null
titleLabel: Title
titleTranslationKeyFormat: null
titleTranslationMethod: site
