allowRepeatingEvents: true
color: '#791C08'
description: ''
descriptionFieldHandle: ''
fieldLayout:
  tabs:
    -
      elementCondition: null
      elements:
        -
          dateAdded: '2024-11-12T10:48:26+00:00'
          elementCondition: null
          fieldUid: 90d007fb-964b-4788-b672-633d855a0058 # Rich Text
          handle: null
          includeInCards: false
          instructions: null
          label: null
          providesThumbs: false
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: 9b623358-9a1b-49eb-9dbe-319e2ddb338a
          userCondition: null
          warning: null
          width: 100
      name: 'Event Details'
      uid: 71536fb3-b1b2-45f7-a321-5f16eec5a12f
      userCondition: null
  uid: d115165f-1a8b-4473-b535-c99ced1dbcf3
handle: worship
hasTitleField: true
icsHash: null
icsTimezone: floating
locationFieldHandle: ''
name: Worship
siteSettings:
  0fba541c-ab52-4012-be55-4eaff00674d1:
    enabledByDefault: true
    hasUrls: true
    siteId: f627def0-bb59-4992-ae44-aef0dfb97c08 # Little Church
    template: worship/_entry
    uriFormat: 'worship/{slug}'
titleFormat: ''
titleLabel: Title
titleTranslationKeyFormat: ''
titleTranslationMethod: none
