baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Little Church'
primary: true
siteGroup: be991be1-9fbd-4fb8-9e2b-19282b305c62 # Little Church
sortOrder: 1
