altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  a00bc44b-1f91-4197-abe8-337b1a227bbb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-14T16:03:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 482589fc-c2b4-46cd-92cc-0cf4ec55e6b9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-14T16:07:46+00:00'
            elementCondition: null
            fieldUid: 820e255c-6450-4806-b5ca-85831d8a7c7f # Plain Text
            handle: caption
            includeInCards: false
            instructions: null
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81151698-61e0-4b5d-adc2-c60c90518b62
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a436a44b-fee0-46a0-88f3-ade1ceb6bbf3
        userCondition: null
fs: eventImages
handle: eventImages
name: 'Event Images'
sortOrder: 10
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
