altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  ecd204af-ba42-4213-a57f-79c86e135781:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-04T10:21:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 7349be5e-0e09-438e-95ab-48fae2933da5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a9e5bd98-0faa-4b3a-a8fc-ee3061bc87b7
        userCondition: null
fs: FeatureImages
handle: FeatureImages
name: 'Feature Images'
sortOrder: 7
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
