altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  690ea02b-008c-4ea1-81f1-e6065db129a5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-19T16:31:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0881bf2d-172c-497d-8029-03e991e6d555
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-10-19T17:16:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 0f1ff995-ec90-4af5-841f-48db6a981b69
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-19T17:17:36+00:00'
            elementCondition: null
            fieldUid: 820e255c-6450-4806-b5ca-85831d8a7c7f # Plain Text
            handle: caption
            includeInCards: false
            instructions: 'A caption for the image '
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7657dd66-fc32-4ec6-b2bf-2a31bfbcd54c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eccef903-680c-4530-be7a-d3a2e6956836
        userCondition: null
fs: heroImage
handle: heroImages
name: 'Hero Images'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
