altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  b1449c21-371e-48b2-81da-d893d48dfeee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-19T21:37:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d568a2c1-e365-4450-99e2-341c5f0f8e6a
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-10-19T21:39:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 77655ff7-f4c4-46c6-9802-108b4de37a58
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a885ec50-b2fe-40a5-8e63-7e77d3f3c142
        userCondition: null
fs: homepageCarouselImages
handle: homepageCarouselImages
name: 'Homepage Carousel Images'
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
