altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  1a96c930-6327-48e8-a734-98ab98ddfb53:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-10T12:03:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0a118fc7-8e71-4acb-9ed3-968f70f478f5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d47d36e0-ae12-4854-8788-f561997e57cd
        userCondition: null
fs: inContentImages
handle: inContentImages
name: 'In-content Images'
sortOrder: 8
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
