columnSuffix: null
handle: audioFile
instructions: null
name: 'Audio File'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: false
  allowedKinds:
    - audio
    - compressed
  branchLimit: null
  defaultUploadLocationSource: 'volume:272db05d-f0fc-489d-9a91-32658794ef35' # Audio Sermon Files
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:272db05d-f0fc-489d-9a91-32658794ef35' # Audio Sermon Files
  restrictedLocationSubpath: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:272db05d-f0fc-489d-9a91-32658794ef35' # Audio Sermon Files
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
