columnSuffix: null
handle: featuredSections
instructions: null
name: 'Featured Sections'
searchable: true
settings:
  createButtonLabel: null
  entryTypes:
    - 27c04a34-53b5-4eaf-a615-91ca4dd52dd5 # Image
    - c9a7a600-9d0b-49e7-abe5-92407d1134b0 # Backdrop
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
