columnSuffix: null
handle: richTextContent
instructions: null
name: 'Rich Text Content'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: c243e913-1c84-463a-bbcb-327b23ff279a # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
