dateModified: 1730278911
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: singles
      tableAttributes:
        - status
        - link
      type: native
    -
      heading: Homepage
      type: heading
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: 'section:3f15b324-fa65-485b-ab56-f9bfed089117' # Homepage Carousel
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: 'Primary Pages'
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:612cf07a-8adc-436d-8d30-04c51e6251c6' # About
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: 'section:f3ad64b9-df55-4707-9d73-70653a4ee4f9' # Worship
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:cf79e9cc-32bf-4f52-90d6-6002f2370405' # Music
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:bfa7add0-6499-4af5-8d33-4dc3e2e262ad' # Education
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: 'Secondary Pages'
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:4de8895d-cb53-4939-90f8-d37639e60da3' # Virtual Tour
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Channels
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:29691dec-8406-465e-bd7f-694f6a1776ff' # Blog
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: ''
      type: heading
    -
      key: 'section:0230f447-379b-4039-be7e-8a8160c130fd' # Audio Sermons
      type: native
email:
  fromEmail: carl@avidanodigital.com
  fromName: 'Little Church'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  audioSermonMp3s:
    hasUrls: true
    name: 'Audio Sermon MP3s'
    settings:
      path: '@webroot/mp3/uploads/sermons'
    type: craft\fs\Local
    url: '@web/mp3/uploads/sermons'
  blog:
    hasUrls: true
    name: Blog
    settings:
      path: '@webroot/images/uploads/blog'
    type: craft\fs\Local
    url: '@web/images/uploads/blog'
  figureImages:
    hasUrls: true
    name: 'Figure Images'
    settings:
      path: '@webroot/images/uploads/figure'
    type: craft\fs\Local
    url: '@web/images/uploads/figure'
  heroImages:
    hasUrls: true
    name: 'Hero Images'
    settings:
      path: '@webroot/images/uploads/hero'
    type: craft\fs\Local
    url: '@web/images/uploads/hero'
  homepageCarouselImages:
    hasUrls: true
    name: 'Homepage Carousel Images'
    settings:
      path: '@webroot/images/uploads/homepage-carousel'
    type: craft\fs\Local
    url: '@web/images/uploads/homepage-carousel'
  virtualTourImages:
    hasUrls: true
    name: 'Virtual Tour Images'
    settings:
      path: '@webroot/images/uploads/virtual-tour'
    type: craft\fs\Local
    url: '@web/images/uploads/virtual-tour'
meta:
  __names__:
    2f747c28-c7c2-4200-a471-390a2e529c99: 'Figure Image Full' # Figure Image Full
    3f15b324-fa65-485b-ab56-f9bfed089117: 'Homepage Carousel' # Homepage Carousel
    4de8895d-cb53-4939-90f8-d37639e60da3: 'Virtual Tour' # Virtual Tour
    5a15575b-ec2e-47c3-bd00-eb854f1d8055: 'Text Content' # Text Content
    5b9003a1-5077-4296-9639-f03328dd74a2: 'Virtual Tour Images' # Virtual Tour Images
    5da48b70-636f-4798-99d0-24e2899dff02: 'Link URL' # Link URL
    6f5da975-9b06-4385-a972-594aea2d9f04: 'Adult Education' # Adult Education
    6fded0a5-09f9-4885-9b87-14e039c52a6c: 'Link Field' # Link Field
    7e6327ec-021c-419b-a22d-fc3e845dc10f: 'Figure Image Right' # Figure Image Right
    7e837081-2d44-4b75-914c-abca14574951: Date # Date
    27c04a34-53b5-4eaf-a615-91ca4dd52dd5: Image # Image
    41ea8475-5a25-4156-99a9-75f192140d9c: 'Homepage Carousel Images' # Homepage Carousel Images
    45ab6eb6-a238-4395-8d2d-7a851616aed6: 'Call to Action' # Call to Action
    46c2bc01-7fec-4a8d-9e8f-c578c727a0e3: 'Figure Image Right' # Figure Image Right
    67cb7d46-6622-4ee4-8930-b7fe3a6b6655: 'Hompepage Carousel' # Hompepage Carousel
    75c8e62e-3242-4d56-90d1-090d035078f6: 'Figure Image Full' # Figure Image Full
    90d007fb-964b-4788-b672-633d855a0058: 'Rich Text' # Rich Text
    92eb37bb-240d-4363-ac53-88e9360941e8: 'Blog Images' # Blog Images
    0230f447-379b-4039-be7e-8a8160c130fd: 'Audio Sermons' # Audio Sermons
    272db05d-f0fc-489d-9a91-32658794ef35: 'Audio Sermon Files' # Audio Sermon Files
    312a0d44-7d08-4c21-bc00-91291780659b: 'Public Schema' # Public Schema
    612cf07a-8adc-436d-8d30-04c51e6251c6: About # About
    619a0795-e1df-4a64-ba8a-f51f8d892ef8: Visit # Visit
    631b3d2c-5ba4-4914-be51-49de4fe03310: 'Audio Sermon' # Audio Sermon
    649c5a54-f759-4177-990f-60a9da779147: 'Blog Article' # Blog Article
    820a6717-36a8-4b5c-819b-cbdc9e036334: 'Article Content Matrix' # Article Content Matrix
    820e255c-6450-4806-b5ca-85831d8a7c7f: 'Plain Text' # Plain Text
    979c8d61-727b-4c46-ab40-83a3561c192a: 'Hero Images' # Hero Images
    4573cb02-ab7d-471a-80a1-93b140d3422a: 'Introduction Title' # Introduction Title
    6180f8f9-5c6e-408f-898a-bc265d3dab24: 'Call to Action' # Call to Action
    6453b749-5f18-4ffc-b62a-393fa9752a52: 'Hero Image' # Hero Image
    8548ad6c-0d95-4934-8408-543b298b0227: 'Figure Image Horizontal' # Figure Image Horizontal
    8827b8d4-2266-4f88-840c-c506b19dafb0: Image # Image
    24446aa6-8005-424a-8454-e760a87e7bb5: Standard # Standard
    29691dec-8406-465e-bd7f-694f6a1776ff: Blog # Blog
    62967cc3-ad04-4380-8c1e-1a8c19ab8663: 'Figure Images' # Figure Images
    661393a2-0468-49cc-8a89-0a450670c96d: 'Figure Image Vertical' # Figure Image Vertical
    aebde1b3-bc64-4a0d-a85d-dbb5bbb3e331: Homepage # Homepage
    b9395e1a-8d3b-4b8f-aafe-3eab9556b505: 'Primary Page Article' # Primary Page Article
    be991be1-9fbd-4fb8-9e2b-19282b305c62: 'Little Church' # Little Church
    bfa7add0-6499-4af5-8d33-4dc3e2e262ad: Education # Education
    c7d153a5-be7a-4158-94da-72e77d34ffbe: 'Audio File' # Audio File
    c243e913-1c84-463a-bbcb-327b23ff279a: Simple # Simple
    cadcecb7-766f-4de8-bee3-62b75a1e2092: 'Tour Highlight' # Tour Highlight
    cf79e9cc-32bf-4f52-90d6-6002f2370405: Music # Music
    d19a47f7-e578-47f9-afb6-1d31e1066065: 'Blog Article' # Blog Article
    dff320e3-08a7-4091-a328-0a3aa8fc2b82: 'Blog Image' # Blog Image
    f3ad64b9-df55-4707-9d73-70653a4ee4f9: Worship # Worship
    f3e168c6-269e-4407-91bb-1679ca597acb: 'Figure Image Enlarge' # Figure Image Enlarge
    f627def0-bb59-4992-ae44-aef0dfb97c08: 'Little Church' # Little Church
    f8355048-22c0-4c2d-8873-4db92a78ab46: 'Virtual Tour Image' # Virtual Tour Image
    fce93b65-4251-416d-9a60-b4bdd015eb33: Homepage # Homepage
    fdcba0b0-5a7a-4a08-b572-3f2b31afb9a1: 'Virtual Tour Image' # Virtual Tour Image
    ffa934d2-edc4-4201-869b-2aef62147aa3: Default # Default
plugins:
  calendar:
    edition: pro
    enabled: true
    licenseKey: TAT0KQ80MC7YUFDGUON18YTP
    schemaVersion: 5.0.1
    settings:
      allDay: false
      authoredEventEditOnly: false
      defaultView: day
      demoBannerDisabled: true
      descriptionFieldHandle: null
      eventDuration: 60
      firstDayOfWeek: -1
      guestAccess: null
      locationFieldHandle: null
      overlapThreshold: 5
      pluginName: Events
      quickCreateEnabled: false
      showDisabledEvents: false
      showMiniCal: false
      timeFormat: auto
      timeInterval: 30
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      allowedMessageFields: null
      prependSender: 'On behalf of'
      prependSubject: 'New message from Little Church'
      successFlashMessage: 'Your message has been sent.'
      toEmail: cavidano@gmail.com
system:
  edition: solo
  live: true
  name: 'Little Church'
  retryDuration: null
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
