dateModified: 1729250525
email:
  fromEmail: carl@avidanodigital.com
  fromName: 'Little Church'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    312a0d44-7d08-4c21-bc00-91291780659b: 'Public Schema' # Public Schema
    be991be1-9fbd-4fb8-9e2b-19282b305c62: 'Little Church' # Little Church
    f627def0-bb59-4992-ae44-aef0dfb97c08: 'Little Church' # Little Church
system:
  edition: solo
  live: true
  name: 'Little Church'
  retryDuration: null
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
