dateModified: 1731602101
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: true
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - title
        - asc
      disabled: true
      key: singles
      tableAttributes:
        - status
        - link
      type: native
    -
      heading: Homepage
      type: heading
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: b4bc74aa-31cf-459e-b3c0-3425128a0aad
            values:
              - fce93b65-4251-416d-9a60-b4bdd015eb33 # Homepage
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:b580a3c7-480b-4137-b72b-460f537f3e49'
      label: Homepage
      tableAttributes: '-'
      type: custom
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: 'section:3f15b324-fa65-485b-ab56-f9bfed089117' # Homepage Carousel
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: 'Primary Pages'
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:612cf07a-8adc-436d-8d30-04c51e6251c6' # About
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:f3ad64b9-df55-4707-9d73-70653a4ee4f9' # Worship
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:cf79e9cc-32bf-4f52-90d6-6002f2370405' # Music
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:bfa7add0-6499-4af5-8d33-4dc3e2e262ad' # Education
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: 'Secondary Pages'
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:4de8895d-cb53-4939-90f8-d37639e60da3' # Virtual Tour
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 626d8c08-d451-4dab-9b66-12dc867892d8
            values:
              - 619a0795-e1df-4a64-ba8a-f51f8d892ef8 # Visit
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:1b39c438-edab-49a2-a264-15f2211725cc'
      label: Visit
      tableAttributes: '-'
      type: custom
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:29691dec-8406-465e-bd7f-694f6a1776ff' # Blog
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Misc
      type: heading
    -
      key: 'section:0230f447-379b-4039-be7e-8a8160c130fd' # Audio Sermons
      type: native
    -
      key: 'section:3aa3f6ab-edbb-4cf9-aa53-ba17f5c05da2' # Staff Bios
      type: native
email:
  fromEmail: carl@avidanodigital.com
  fromName: 'Little Church'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  FeatureImages:
    hasUrls: true
    name: 'Feature Images'
    settings:
      path: '@webroot/images/uploads/feature'
    type: craft\fs\Local
    url: '@web/images/uploads/feature'
  audioSermonMp3s:
    hasUrls: true
    name: 'Audio Sermon MP3s'
    settings:
      path: '@webroot/mp3/uploads/sermons'
    type: craft\fs\Local
    url: '@web/mp3/uploads/sermons'
  blogImages:
    hasUrls: true
    name: 'Blog Images'
    settings:
      path: '@webroot/images/uploads/blog'
    type: craft\fs\Local
    url: '@web/images/uploads/blog'
  eventImages:
    hasUrls: true
    name: 'Event Images'
    settings:
      path: '@webroot/images/uploads/event'
    type: craft\fs\Local
    url: '@web/images/uploads/event'
  figureImages:
    hasUrls: true
    name: 'Figure Images'
    settings:
      path: '@webroot/images/uploads/figure'
    type: craft\fs\Local
    url: '@web/images/uploads/figure'
  heroImages:
    hasUrls: true
    name: 'Hero Images'
    settings:
      path: '@webroot/images/uploads/hero'
    type: craft\fs\Local
    url: '@web/images/uploads/hero'
  homepageCarouselImages:
    hasUrls: true
    name: 'Homepage Carousel Images'
    settings:
      path: '@webroot/images/uploads/homepage-carousel'
    type: craft\fs\Local
    url: '@web/images/uploads/homepage-carousel'
  inContentImages:
    hasUrls: true
    name: 'In-content Images'
    settings:
      path: '@webroot/images/uploads/inContent'
    type: craft\fs\Local
    url: '@web/images/uploads/inContent'
  staffPortraitImages:
    hasUrls: true
    name: 'Staff Portrait Images'
    settings:
      path: '@webroot/images/uploads/staffPortrait'
    type: craft\fs\Local
    url: '@web/images/uploads/staffPortrait'
  virtualTourImages:
    hasUrls: true
    name: 'Virtual Tour Images'
    settings:
      path: '@webroot/images/uploads/virtual-tour'
    type: craft\fs\Local
    url: '@web/images/uploads/virtual-tour'
meta:
  __names__:
    1c7365c4-cfdc-40d5-9fa9-73682e32a75f: Default # Default
    2dcf23aa-ca5c-4c07-9b15-38f9d6b99b7e: Default # Default
    2f747c28-c7c2-4200-a471-390a2e529c99: 'Figure Image Full' # Figure Image Full
    3aa3f6ab-edbb-4cf9-aa53-ba17f5c05da2: 'Staff Bios' # Staff Bios
    3f15b324-fa65-485b-ab56-f9bfed089117: 'Homepage Carousel' # Homepage Carousel
    4de8895d-cb53-4939-90f8-d37639e60da3: 'Virtual Tour' # Virtual Tour
    5a15575b-ec2e-47c3-bd00-eb854f1d8055: 'Text Content' # Text Content
    5b9003a1-5077-4296-9639-f03328dd74a2: 'Virtual Tour Images' # Virtual Tour Images
    5da48b70-636f-4798-99d0-24e2899dff02: 'Link URL' # Link URL
    6a6ae7db-e603-4a9d-8d0f-562e07f220c7: 'Feature Images' # Feature Images
    6aa94d24-4ad6-4dfd-a774-caf5f96339c3: 'Icon Handle' # Icon Handle
    6fded0a5-09f9-4885-9b87-14e039c52a6c: 'Link Field' # Link Field
    7e6327ec-021c-419b-a22d-fc3e845dc10f: 'Figure Image Right' # Figure Image Right
    7e837081-2d44-4b75-914c-abca14574951: Date # Date
    9af1c194-2693-4d86-9eee-bbff86eaae7a: 'Staff Bio' # Staff Bio
    9b8fb642-9998-4f11-ac4f-92e53344af2c: 'Staff Portrait Images' # Staff Portrait Images
    12ddbb21-575e-4a98-b2de-353d6663fad9: Event # Event
    27c04a34-53b5-4eaf-a615-91ca4dd52dd5: Image # Image
    39af2a3a-aab0-4110-beef-2c6c8d52eb26: 'Event Image' # Event Image
    41ea8475-5a25-4156-99a9-75f192140d9c: 'Homepage Carousel Images' # Homepage Carousel Images
    45ab6eb6-a238-4395-8d2d-7a851616aed6: 'Call to Action' # Call to Action
    46c2bc01-7fec-4a8d-9e8f-c578c727a0e3: 'Figure Image Right' # Figure Image Right
    67cb7d46-6622-4ee4-8930-b7fe3a6b6655: 'Hompepage Carousel' # Hompepage Carousel
    75c8e62e-3242-4d56-90d1-090d035078f6: 'Figure Image Full' # Figure Image Full
    86bf3f52-140d-4267-8025-466a1c2b90d7: 'Specialty Banner' # Specialty Banner
    90d007fb-964b-4788-b672-633d855a0058: 'Event Details' # Event Details
    92eb37bb-240d-4363-ac53-88e9360941e8: 'Blog Images' # Blog Images
    133d1b38-9cb8-4cd0-8001-01d0f0fe0dd3: Event # Event
    0230f447-379b-4039-be7e-8a8160c130fd: 'Audio Sermons' # Audio Sermons
    272db05d-f0fc-489d-9a91-32658794ef35: 'Audio Sermon Files' # Audio Sermon Files
    296e8f4d-5cda-4e81-996a-3c97f9404a0a: 'Social Media URL' # Social Media URL
    312a0d44-7d08-4c21-bc00-91291780659b: 'Public Schema' # Public Schema
    612cf07a-8adc-436d-8d30-04c51e6251c6: About # About
    619a0795-e1df-4a64-ba8a-f51f8d892ef8: Visit # Visit
    631b3d2c-5ba4-4914-be51-49de4fe03310: 'Audio Sermon' # Audio Sermon
    649c5a54-f759-4177-990f-60a9da779147: 'Blog Article' # Blog Article
    820a6717-36a8-4b5c-819b-cbdc9e036334: 'Article Content Matrix' # Article Content Matrix
    820e255c-6450-4806-b5ca-85831d8a7c7f: 'Plain Text' # Plain Text
    979c8d61-727b-4c46-ab40-83a3561c192a: 'Hero Images' # Hero Images
    4024edd3-9d2b-446a-a6dd-48f15e0fc637: 'Featured Pages' # Featured Pages
    4134d018-56ae-4e27-b184-ec3091b3ef44: 'Social Media Channels' # Social Media Channels
    4573cb02-ab7d-471a-80a1-93b140d3422a: 'Introduction Title' # Introduction Title
    6180f8f9-5c6e-408f-898a-bc265d3dab24: 'Call to Action' # Call to Action
    6453b749-5f18-4ffc-b62a-393fa9752a52: 'Hero Image' # Hero Image
    8374da94-9d3b-49d7-9f8c-293a41e4ada7: 'Event Images' # Event Images
    8548ad6c-0d95-4934-8408-543b298b0227: 'Figure Image Horizontal' # Figure Image Horizontal
    8827b8d4-2266-4f88-840c-c506b19dafb0: Image # Image
    24446aa6-8005-424a-8454-e760a87e7bb5: Standard # Standard
    24715bb8-b7af-4e84-8803-7a8bfb40b984: 'Social Media Channel' # Social Media Channel
    29691dec-8406-465e-bd7f-694f6a1776ff: Blog # Blog
    62967cc3-ad04-4380-8c1e-1a8c19ab8663: 'Figure Images' # Figure Images
    96916aa2-1b5e-429b-85fa-747aa201e6dc: 'Feature Image' # Feature Image
    123643e3-79a8-4fae-ba43-55c05a270bc5: 'Staff Bio Image' # Staff Bio Image
    211161e3-d705-4c10-acea-25a14bd50f23: Worship # Worship
    661393a2-0468-49cc-8a89-0a450670c96d: 'Figure Image Vertical' # Figure Image Vertical
    aebde1b3-bc64-4a0d-a85d-dbb5bbb3e331: 'Homepage Layout' # Homepage Layout
    b9395e1a-8d3b-4b8f-aafe-3eab9556b505: 'Primary Page Article' # Primary Page Article
    be991be1-9fbd-4fb8-9e2b-19282b305c62: 'Little Church' # Little Church
    bfa7add0-6499-4af5-8d33-4dc3e2e262ad: Education # Education
    c7d153a5-be7a-4158-94da-72e77d34ffbe: 'Audio File' # Audio File
    c243e913-1c84-463a-bbcb-327b23ff279a: Simple # Simple
    cadcecb7-766f-4de8-bee3-62b75a1e2092: 'Tour Highlight' # Tour Highlight
    cf79e9cc-32bf-4f52-90d6-6002f2370405: Music # Music
    d2c0cf4c-216c-48fd-ba4e-df85d29d73eb: 'In-content Images' # In-content Images
    d19a47f7-e578-47f9-afb6-1d31e1066065: 'Blog Article' # Blog Article
    d75aec9b-bec5-491a-afca-804afad393e2: 'Social Media' # Social Media
    dff320e3-08a7-4091-a328-0a3aa8fc2b82: 'Blog Image' # Blog Image
    e404e713-c6b5-42aa-9614-6eab00ed8cc5: 'Spotlight Video URL' # Spotlight Video URL
    f3ad64b9-df55-4707-9d73-70653a4ee4f9: Worship # Worship
    f3e168c6-269e-4407-91bb-1679ca597acb: 'Figure Image Enlarge' # Figure Image Enlarge
    f19c1853-f1a3-4c74-b351-7e640b63b495: 'In-content Image' # In-content Image
    f627def0-bb59-4992-ae44-aef0dfb97c08: 'Little Church' # Little Church
    f8355048-22c0-4c2d-8873-4db92a78ab46: 'Virtual Tour Image' # Virtual Tour Image
    fce93b65-4251-416d-9a60-b4bdd015eb33: Homepage # Homepage
    fdcba0b0-5a7a-4a08-b572-3f2b31afb9a1: 'Virtual Tour Image' # Virtual Tour Image
plugins:
  calendar:
    edition: pro
    enabled: true
    licenseKey: USMSYGWPM856CQWAWMTXDIJN
    schemaVersion: 5.0.1
    settings:
      allDay: false
      authoredEventEditOnly: false
      defaultView: month
      demoBannerDisabled: true
      descriptionFieldHandle: null
      eventDuration: 60
      firstDayOfWeek: -1
      guestAccess: null
      locationFieldHandle: null
      overlapThreshold: 5
      pluginName: Events
      quickCreateEnabled: true
      showDisabledEvents: true
      showMiniCal: true
      timeFormat: auto
      timeInterval: 30
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  codefield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      allowedMessageFields: null
      prependSender: 'On behalf of'
      prependSubject: 'New message from Little Church'
      successFlashMessage: 'Your message has been sent.'
      toEmail: cavidano@gmail.com
  cp-nav:
    edition: standard
    enabled: true
    schemaVersion: 2.0.11
system:
  edition: solo
  live: true
  name: 'Little Church'
  retryDuration: null
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
