currLabel: Events
customIcon: null
enabled: true
handle: calendar
icon: /Users/carlandjohnnieavidano/Sites/little-church-2024/vendor/solspace/craft-calendar/packages/plugin/src/icon-mask.svg
layout: 1c7365c4-cfdc-40d5-9fa9-73682e32a75f # Default
level: 1
newWindow: false
parent: null
prevLabel: Events
prevLevel: 1
prevParent: null
prevUrl: calendar
sortOrder: 5
type: plugin
url: calendar
