currLabel: Entries
customIcon: null
enabled: true
handle: entries
icon: newspaper
layout: 1c7365c4-cfdc-40d5-9fa9-73682e32a75f # Default
level: 1
newWindow: false
parent: null
prevLabel: Entries
prevLevel: 1
prevParent: null
prevUrl: entries
sortOrder: 2
type: craft
url: entries
