currLabel: Events
customIcon: null
enabled: true
handle: events
icon: null
layout: 1c7365c4-cfdc-40d5-9fa9-73682e32a75f # Default
level: 2
newWindow: false
parent: cc5beb92-052d-4a69-ba50-b240baa46a0c
prevLabel: Events
prevLevel: 2
prevParent: cc5beb92-052d-4a69-ba50-b240baa46a0c
prevUrl: calendar/events
sortOrder: 19
type: plugin
url: calendar/events
