currLabel: Globals
customIcon: null
enabled: true
handle: globals
icon: globe
layout: 1c7365c4-cfdc-40d5-9fa9-73682e32a75f # Default
level: 1
newWindow: false
parent: null
prevLabel: Globals
prevLevel: 1
prevParent: null
prevUrl: globals
sortOrder: 3
type: craft
url: globals
