currLabel: Month
customIcon: null
enabled: true
handle: month
icon: null
layout: 1c7365c4-cfdc-40d5-9fa9-73682e32a75f # Default
level: 2
newWindow: false
parent: fc476b5f-f8f4-4ef8-a299-603439fdcbc7
prevLabel: Month
prevLevel: 2
prevParent: fc476b5f-f8f4-4ef8-a299-603439fdcbc7
prevUrl: calendar/view/month
sortOrder: 6
type: plugin
url: calendar/view/month
