currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: null
layout: 1c7365c4-cfdc-40d5-9fa9-73682e32a75f # Default
level: 2
newWindow: false
parent: da4e5afb-0c1b-4afc-8c02-8c0c2348d58e
prevLabel: Settings
prevLevel: 2
prevParent: da4e5afb-0c1b-4afc-8c02-8c0c2348d58e
prevUrl: calendar/settings
sortOrder: 21
type: plugin
url: calendar/settings
