currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: gear
layout: 1c7365c4-cfdc-40d5-9fa9-73682e32a75f # Default
level: 1
newWindow: false
parent: null
prevLabel: Settings
prevLevel: 1
prevParent: null
prevUrl: settings
sortOrder: 13
type: craft
url: settings
