currLabel: Utilities
customIcon: null
enabled: true
handle: utilities
icon: wrench
layout: 1c7365c4-cfdc-40d5-9fa9-73682e32a75f # Default
level: 1
newWindow: false
parent: null
prevLabel: Utilities
prevLevel: 1
prevParent: null
prevUrl: utilities
sortOrder: 12
type: craft
url: utilities
