defaultPlacement: end
enableVersioning: true
entryTypes:
  - 631b3d2c-5ba4-4914-be51-49de4fe03310 # Audio Sermon
handle: audioSermons
maxAuthors: 1
name: 'Audio Sermons'
propagationMethod: all
siteSettings:
  f627def0-bb59-4992-ae44-aef0dfb97c08: # Little Church
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
