defaultPlacement: end
enableVersioning: true
entryTypes:
  - b9395e1a-8d3b-4b8f-aafe-3eab9556b505 # Primary Page Article
handle: music
maxAuthors: 1
name: Music
propagationMethod: all
siteSettings:
  f627def0-bb59-4992-ae44-aef0dfb97c08: # Little Church
    enabledByDefault: true
    hasUrls: true
    template: about/_entry.twig
    uriFormat: 'music/{slug}'
structure:
  maxLevels: 1
  uid: 0e69c9c3-686b-4a41-b530-53e9dbe280bf
type: structure
