tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2024-12-23T04:09:41-08:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 2914fe81-6e52-432a-bfeb-308917942469
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2024-12-23T04:09:41-08:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: d00f1a34-66f6-459d-9b46-2919439daf9e
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-12-23T04:09:41-08:00'
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 2a7089b6-146e-4d8a-b370-ea7742391842
        userCondition: null
        warning: null
    name: Content
    uid: c8bc4d08-7e2b-44a8-a56f-fff6ae163a9c
    userCondition: null
